DROP TABLE MAEDR_STATE_INFO IF EXISTS CASCADE;
-- :

CREATE CACHED TABLE MAEDR_STATE_INFO 
(
    LASTMODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	TRACKID   VARCHAR(255) NULL,
	KEYID   VARCHAR(255) NOT NULL,
	BININFO LONGVARBINARY NOT NULL,
	EXPIRYTS  TIMESTAMP NULL,
	PRIMARY KEY (KEYID),
	UNIQUE (TRACKID)
);
-- :

CREATE INDEX MAEDR_STATE_INFO_IDX_1 ON MAEDR_STATE_INFO(EXPIRYTS);
-- :

GRANT ALL ON MAEDR_STATE_INFO TO PUBLIC;
-- :
