IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id=object_id('MAEDR_STATE_INFO')) DROP TABLE MAEDR_STATE_INFO;
-- :


CREATE TABLE MAEDR_STATE_INFO 
(
    LASTMODIFIED DATETIME DEFAULT CURRENT_TIMESTAMP,
    TRACKID   VARCHAR(255) NOT NULL,
    KEYID   VARCHAR(255) NOT NULL,
    BININFO IMAGE NOT NULL,
    EXPIRYTIME  DATETIME NOT NULL,
    PRIMARY KEY (KEYID),
    UNIQUE (TRACKID)
);
-- :

CREATE INDEX MAEDR_STATE_INFO_IDX_1 ON MAEDR_STATE_INFO(EXPIRYTIME);
-- :
