DROP TABLE IF EXISTS MAEDR_STATE_INFO;
-- :

CREATE TABLE MAEDR_STATE_INFO 
(
    LASTMODIFIED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TRACKID   VARCHAR(255) NOT NULL,
    KEYID   VARCHAR(255) NOT NULL,
    BININFO LONGBLOB NOT NULL,
    EXPIRYTIME  TIMESTAMP NOT NULL,
    PRIMARY KEY (KEYID),
    UNIQUE (TRACKID)
) Type=InnoDB;
-- :

CREATE INDEX MAEDR_STATE_INFO_IDX_1 ON MAEDR_STATE_INFO(EXPIRYTIME);
-- :
