DROP TABLE MAEDR_STATE_INFO CASCADE CONSTRAINTS;
-- :

CREATE TABLE MAEDR_STATE_INFO 
(
    LASTMODIFIED TIMESTAMP DEFAULT SYSTIMESTAMP,
    TRACKID   VARCHAR2(255) NOT NULL,
    KEYID   VARCHAR2(255) NOT NULL,
    BININFO BLOB NOT NULL,
    EXPIRYTIME  TIMESTAMP NOT NULL,
    PRIMARY KEY (KEYID),
    UNIQUE (TRACKID)
);
-- :

CREATE INDEX MAEDR_STATE_INFO_IDX_1 ON MAEDR_STATE_INFO(EXPIRYTIME);
-- :
