/*??
 * COPYRIGHT (C) 2010-2011 CHERIMOIA LLC. ALL RIGHTS RESERVED.
 *
 * THIS IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR
 * MODIFY IT UNDER THE TERMS OF THE APACHE LICENSE, 
 * VERSION 2.0 (THE "LICENSE").
 *
 * THIS LIBRARY IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 *   
 * SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS 
 * AND LIMITATIONS UNDER THE LICENSE.
 *
 * You should have received a copy of the Apache License
 * along with this distribution; if not, you may obtain a copy of the 
 * License at 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 ??*/
 

package com.zotoh.maedr.device;

import java.io.File;

import static com.zotoh.core.util.StrUte.*;

/**
 * An Event generated by the FilePicker device.  This event carries the
 * reference to the file which has been picked up by the device.
 * 
 * @author kenl
 */
public class FileEvent extends Event {

    private static final long serialVersionUID = 4218879282887901571L;
    private final File _file;
    private final String _origPath;
    private transient Exception _error;
    
    /**
     * @param dev
     * @param originalFile
     * @param f
     * @param e
     */
    public FileEvent(Device dev, String originalFile, File f, Exception e)    {
        super(dev);
        _error=e;
        _file=f;
        _origPath=nsb(originalFile);
    }
    
    /**
     * @param dev
     * @param f
     */
    public FileEvent(Device dev, File f)    {
        this(dev, "", f, null);
    }

    /**
     * @return
     */
    public String getOrigFilePath() { return _origPath; }
    
    /**
     * @return
     */
    public File getFile() {        return _file;    }
    
    /**
     * @return
     */
    public boolean hasError() { return _error != null ; }
        
    /**
     * @return
     */
    public Exception getError() { return _error; }
    
}
