/*??
 * COPYRIGHT (C) 2010 CHERIMOIA LLC. ALL RIGHTS RESERVED.
 *
 * THIS IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR
 * MODIFY IT UNDER THE TERMS OF THE APACHE LICENSE, 
 * VERSION 2.0 (THE "LICENSE").
 *
 * THIS LIBRARY IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 *   
 * SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS 
 * AND LIMITATIONS UNDER THE LICENSE.
 *
 * You should have received a copy of the Apache License
 * along with this distribution; if not, you may obtain a copy of the 
 * License at 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 ??*/


package com.zotoh.maedr.device;

import javax.jms.Message;

/**
 * Events generated by the JMS device.  This event carries the actual JMS message received by the device.
 * 
 * @author kenl
 */
public class JmsEvent extends Event {

    private static final long serialVersionUID = 7015919518719229577L;
    private final Message _msg;
    
    /**
     * @param dev
     * @param msg
     */
    public JmsEvent(Device dev, Message msg)     {
        super(dev);
        _msg= msg;
    }
    
    /**
     * @return
     */
    public Message getMsg() {        return _msg;    }
        
}
