/*??
 * COPYRIGHT (C) 2011 CHERIMOIA LLC. ALL RIGHTS RESERVED.
 *
 * THIS IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR
 * MODIFY IT UNDER THE TERMS OF THE APACHE LICENSE, 
 * VERSION 2.0 (THE "LICENSE").
 *
 * THIS LIBRARY IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 *   
 * SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS 
 * AND LIMITATIONS UNDER THE LICENSE.
 *
 * You should have received a copy of the Apache License
 * along with this distribution; if not, you may obtain a copy of the 
 * License at 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 ??*/

package com.zotoh.maedr.device;

import com.zotoh.maedr.http.UriPathChain;

/**
 * Events generated by a RESTful Http device.  The URL is broken into a
 * chain of paths, taking care of possible Matrix parameters.
 *
 * @author kenl
 */
public class RESTEvent extends HttpEvent {

	private static final long serialVersionUID = -1897104248763361415L;
	private UriPathChain _chain;
	
    /**
     * @param m
     */
    public RESTEvent(Device m) {
        super(m);
    }
    
    /**
     * @param c
     */
    public boolean setUriChain(UriPathChain c) {
    		_chain=c;	
    		return true;
    }
    
    /**
     * @return
     */
    public UriPathChain getPath() { return _chain; }
    
}
