/*??
 * COPYRIGHT (C) 2010 CHERIMOIA LLC. ALL RIGHTS RESERVED.
 *
 * THIS IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR
 * MODIFY IT UNDER THE TERMS OF THE APACHE LICENSE, 
 * VERSION 2.0 (THE "LICENSE").
 *
 * THIS LIBRARY IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 *   
 * SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS 
 * AND LIMITATIONS UNDER THE LICENSE.
 *
 * You should have received a copy of the Apache License
 * along with this distribution; if not, you may obtain a copy of the 
 * License at 
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 ??*/
 

package com.zotoh.maedr.device;

/**
 * Events generated by Timer devices.
 *
 * @author kenl
 */
public class TimerEvent extends Event {
    
    private static final long serialVersionUID = 3377494094789182784L;
    private final boolean _repeats;
    
    /**
     * @param dev
     * @param repeating
     */
    public TimerEvent(Device dev, boolean repeating) {
        super(dev);
        _repeats= repeating;
    }
    
    /**
     * @param dev
     */
    public TimerEvent(Device dev) {
        this(dev, false);
    }

    /**
     * @return
     */
    public boolean isRepeating() {        return _repeats;    }

    
}
